### ISSUE TITLE
Issue with namespaces

### ISSUE THREAD

**Issue by damian-lb** [lorenzo/cakephp-sqs#10]
Hi

As far as I know, CakePHP 2 does not support namespaces. However, this plugin uses them. I have followed the installation instructions, however, I am unable to use the  SQS.SimpleQueue class due to a missing namespace.

I receive the following error when trying to execute ClassRegistry::init('SQS.SimpleQueue')->send('xxx', array('xxx' => 'xxx')); from any controller:

Class 'Aws\Common\Client\AbstractClient' not found

Seeing that this plugin was developed for CakePHP 2.x, I assume I have done something incorrectly in the installation process. Please advise.

**Comment by ryuzee** [comment]
@damian-lb This error message shows that your application could not find a class module included in aws-sdk-php. Please install aws-sdk-php v2.

**Comment by damian-lb** [comment]
Thanks @ryuzee. My mistake was that I did not install CakePHP from composer. I manually edited my boostrap file to include the autoload.php file in the root vendors directory and now it works.
