### ISSUE TITLE
Cake specific debug logging error

### ISSUE THREAD

**Issue by srinivasmangipudi** [lorenzo/cakephp-sqs#11]
I am trying to use your lib, but it fails at these lines in SimpleQueue.php

(line 65) CakeLog::debug(sprintf('Creating background job: %s', $taskName), array('sqs'));
(line 102) CakeLog::write(sprintf('Creating %d messages in queue: %s', count($payloads), $taskName), array('sqs'));

I checked the cake docs and changed it to CakeLog::write() and everything is working.

I am wondering how to handle this, as composer will be run when deploying to production and this might get overwritten and thus fail again.

Thanks.

**Comment by lorenzo** [comment]
I don't understand the question
