### ISSUE TITLE
Composer installing error

### ISSUE THREAD

**Issue by srinivasmangipudi** [lorenzo/cakephp-sqs#12]
I added the lines in composer as mentioned in your help file:

```
"require": {
        "kamisama/cake-resque": "4.1.0",
        "lorenzo/cakephp-sqs": "master"
    },
```

but this throws an error saying that only dev-master is available. when I change it to dev-master it installs correctly. So is dev-master a stable version to use for production?

**Comment by lorenzo** [comment]
it is :)
