### ISSUE TITLE
No inifite loop possible

### ISSUE THREAD

**Issue by felixlehmann** [lorenzo/cakephp-sqs#16]
The method documentation says that setting `iterations` to `-1` will make the process last forever.

But according to the while loop condition, I would say for `-1` it actually never starts, when `$i` is initiated with `0`.

https://github.com/lorenzo/cakephp-sqs/blob/da9045f7659ab51592e5e282827d023eea5599a3/src/Shell/Task/QueueWorkerTask.php#L53

**Comment by luukau** [comment]
Maybe the loop could be amended to look something like:

```
        $i = 0;
        $infinit_loop = ($iterations == -1);
        while (($i < $iterations) || $infinit_loop) {
            foreach ....
                 ... 
            }
            if (!$infinit_loop) $i++;
        }
```
But I'm sure there are more elegant solutions :)

**Comment by lorenzo** [comment]
Try sending a pull request with the fix, please :)

**Comment by felixlehmann** [comment]
I created the pull request
