### ISSUE TITLE
Consider using queue interprop as abstraction for queues

### ISSUE THREAD

**Issue by makasim** [lorenzo/cakephp-sqs#20]
Hello!

Please look at https://github.com/queue-interop/queue-interop project. Using interfaces from it allows us reuse some implementations like enqueue, which supports a lot of transports. You can outsource some code

**Comment by lorenzo** [comment]
This repo is only concerned with SQS, you can take a look at https://github.com/josegonzalez/php-queuesadilla for an implementation using multiple different backends
