### ISSUE TITLE
Unable to send message from within shell when using the QueueWorker task

### ISSUE THREAD

**Issue by aceat64** [lorenzo/cakephp-sqs#6]
I get the following error when attempting to send a message from my worker:

```
2015-04-16 15:46:38 Debug: Creating background job: worker
2015-04-16 15:46:46 Error: [curl] 35:  [url] https://sqs.us-west-2.amazonaws.com/[redacted]
2015-04-16 15:46:46 Error: Could not create background job for task worker
```

Sending works fine in a shell, but only if the QueueWorker task is not being used.

**Comment by aceat64** [comment]
I have narrowed down the issue some more, it only occurs after a fork.

**Comment by lorenzo** [comment]
@aceat64 do you have an idea how to fix this? I'm not very involved into using SQS lately so it will take me some time to actually test and fix this

**Comment by jippi** [comment]
also, forking in php is not a good idea - run multiple processes

**Comment by xtrembaker** [comment]
Hello !

I can't install the plugin using composer. Error thrown is :
> Your requirements could not be resolved to an installable set of packages.
> Problem 1
> - The requested package lorenzo/cakephp-sqs could not be found in any version, there may be a typo in the package name.
> Potential causes:
> - A typo in the package name
>  - The package is not available in a stable-enough version according to your minimum-stability setting
>   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.
> Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Someone's already encountered that error ?

Thanks by advance for your help

**Comment by lorenzo** [comment]
Please open a new ticket as this is a different issue

**Comment by xtrembaker** [comment]
Yes sorry about that !
