### ISSUE TITLE
Can't install the plugin using composer

### ISSUE THREAD

**Issue by xtrembaker** [lorenzo/cakephp-sqs#7]
Hello !

I can't install the plugin using composer. Error thrown is :

Your requirements could not be resolved to an installable set of packages.
Problem 1

The requested package lorenzo/cakephp-sqs could not be found in any version, there may be a typo in the package name. Potential causes:
A typo in the package name
The package is not available in a stable-enough version according to your minimum-stability setting see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details. Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.
Someone's already encountered that error ?

Here is my composer.json file :

{
"require": {
"zircote/swagger-php": "",
"aws/aws-sdk-php": "2.",
"lorenzo/cakephp-sqs": "master"
},
"require-dev": {
"phpunit/phpunit": "3.7.*"
},
"extra": {
"installer-paths": {
"app/Plugin/SQS": ["lorenzo/cakephp-sqs"]
}
}
}
I also tried it with a brand new Cakephp2.X composer file, but still the same error ...

Thanks by advance for your help

**Comment by lorenzo** [comment]
I could get the plugin after running `composer require lorenzo/cakephp-sqs` after adding the `"extra"` part in my `composer.json`

**Comment by xtrembaker** [comment]
OK I was able to install it, but I needed to specify "minimum-stability": "dev" in my composer file.

Thank you
